### ISSUE TITLE
Release 2.6 CD is a bad master

### ISSUE THREAD

**Issue by ramapcsx2** [ShendoXT/biosdumper#2]
Hey,
I wonder whether you could re-master the current CD version.
The mastering tool used put in some nonsense into the sector headers, which won't work on a real machine.
The reason it works when burned to CD is that the CD software (or the drive itself) is correcting all the errors :p 

Maybe it was just wrong settings used, maybe the mastering software is just bad.
A good modern alternative is https://github.com/Lameguy64/mkpsxiso , cheers! :)

**Comment by ramapcsx2** [comment]
The tool put in 0x0A instead of 0x10 here, for example.
https://i.imgur.com/Ww8QWdN.png

**Comment by CWCprime** [comment]
@ramapcsx2 

Are you aware of any alternatives to this homebrew? I'm trying to dump my original PS1 BIOS with this software using an Xstation and Memcard Pro, but can't get the program to launch, just hangs on a black screen. Like you said, looks like a bad CD image that's not working on real hardware.

**Comment by ramapcsx2** [comment]
"A good modern alternative is https://github.com/Lameguy64/mkpsxiso , cheers! :)"
^^

**Comment by ShendoXT** [comment]
Thanks for the heads-up @ramapcsx2. I don't even remember what software I used to master the image.
I think it was either "PsOne ISO Maker PRO" or even older "PSX ISO Maker" :)

@CWCprime Can you try running the new image?

**Comment by CWCprime** [comment]
@ShendoXT Just tried it. Works great now, thanks!

**Comment by ShendoXT** [comment]
Awesome. Thanks for the feedback guys.

**Comment by ramapcsx2** [comment]
Thanks for the update, too :)
